# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# Basic Authentication
# user@example.com: Basic dXNlckBleGFtcGxlLmNvbTp1c2Vy
# curator@example.com: Basic Y3VyYXRvckBleGFtcGxlLmNvbTpjdXJhdG9y
# admin@example.com: Basic YWRtaW5AZXhhbXBsZS5jb206YWRtaW4=

POST http://localhost:8080/books
Content-Type: application/json
Authorization: Basic Y3VyYXRvckBleGFtcGxlLmNvbTpjdXJhdG9y

{
    "isbn": "123456789",
    "title": "mytitle",
    "description": "mydescription",
    "authors": [
        "test"
    ]
}

###

GET http://localhost:8080/books
Accept: application/json
Authorization: Basic dXNlckBleGFtcGxlLmNvbTp1c2Vy

###

GET http://localhost:8080/books/bf0dbaea-3718-4bc3-a7cf-115541454e29
Accept: application/json
Authorization: Basic dXNlckBleGFtcGxlLmNvbTp1c2Vy

###

DELETE http://localhost:8080/books/37afebc5-df42-4452-b4a9-68dda1a7778c
Accept: application/json
Authorization: Basic Y3VyYXRvckBleGFtcGxlLmNvbTpjdXJhdG9y

###

POST http://localhost:8080/books/1c7ad93d-f71d-4a75-912c-928c91a115ec/borrow
Accept: application/json
Authorization: Basic dXNlckBleGFtcGxlLmNvbTp1c2Vy
###

POST http://localhost:8080/books/{id}/return
Accept: application/json
Authorization: Basic dXNlckBleGFtcGxlLmNvbTp1c2Vy

###

