[source,options="nowrap"]
----
package com.example.library.server.config;

...

@EnableWebFluxSecurity
@EnableReactiveMethodSecurity # <1>
public class WebSecurityConfiguration {

    @Bean # <2>
    public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        return http
                .authorizeExchange()
                .matchers(PathRequest.toStaticResources().atCommonLocations()).permitAll() # <3>
                .matchers(EndpointRequest.to("health")).permitAll() # <4>
                .matchers(EndpointRequest.to("info")).permitAll()
                .matchers(EndpointRequest.toAnyEndpoint()).hasRole(Role.ADMIN.name()) # <5>
                .pathMatchers(HttpMethod.POST, "/books").hasRole(Role.CURATOR.name()) # <6>
                .pathMatchers(HttpMethod.DELETE, "/books").hasRole(Role.CURATOR.name())
                .pathMatchers("/users/**").hasRole(Role.ADMIN.name()) # <7>
                .anyExchange().authenticated() # <8>
                .and()
                .httpBasic().and().formLogin().and() # <9>
                .logout().logoutSuccessHandler(logoutSuccessHandler()) # <10>
                .and()
                .build();
    }

    @Bean # <11>
    public ServerLogoutSuccessHandler logoutSuccessHandler() {
        RedirectServerLogoutSuccessHandler logoutSuccessHandler = new RedirectServerLogoutSuccessHandler();
        logoutSuccessHandler.setLogoutSuccessUrl(URI.create("/books"));
        return logoutSuccessHandler;
    }

    @Bean
    public PasswordEncoder passwordEncoder() {
        return PasswordEncoderFactories.createDelegatingPasswordEncoder();
    }

}
----
<1> This adds support for method level authorization
<2> Configures authentication and web layer authorization for all URL's of our REST api
<3> All static resources (favicon.ico, css, images, ...) can be accessed without authentication
<4> Actuator endpoints for _health_ and _info_ can be accessed without authentication
<5> All other actuator endpoints require authentication
<6> Modifying access to books require authenticated user having the 'CURATOR' role
<7> Access to users require authenticated user having the 'ADMIN' role
<8> All other web endpoints require authentication
<9> Authentication can be performed using basic authentication or form based login
<10> After logging out it redirects to URL configured in the logout success handler
<11> The configured login success handler redirects to https://localhost:8080/books[/books] resource