# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/users
Content-Type: application/json

{
    "email": "test@example.com",
    "firstName": "first",
    "lastName": "last",
    "roles": [
        "USER"
    ]
}

###

GET http://localhost:8080/users
Accept: application/json

###

GET http://localhost:8080/users/bae9cf47-9345-4925-acef-edd81883b36d
Accept: application/json

###

DELETE http://localhost:8080/users/bae9cf47-9345-4925-acef-edd81883b36d
Accept: application/json

###


